### ISSUE TITLE
Support for different enviornments

### ISSUE THREAD

**Issue by ahelal** [azavea/ansible-beaver#4]
Hi,

Thank you for your role. I  forked your role and updated to support more dynamic config but this will break your current structure. I am still adding some minor features, but do let me know if you're interested  and would like me to resubmit my code upstream.

Cheers

**Comment by hectcastro** [comment]
Hey @ahelal,

Thanks for making use of our role and opening this issue.

Thus far, our approach to building upon the Beaver role has been creating application specific roles and listing `azavea.beaver` as a dependency. That role is then responsible for log capturing configuration templates, broker configuration, and group modifications. An recent example of that can be found [here](https://github.com/azavea/nyc-trees/tree/develop/deployment/ansible/roles/nyc-trees.beaver).

With regard to your changes, we've run into issue with nested attributes because you generally can't pick and choose a nested attribute to override. Instead, you end up having to override them all.

**Comment by ahelal** [comment]
Hey, 

I understand your position. 1- its base role installs and sets up broker 2- you depend on application role to deploy rest of config .

1) It seems it very redis centric so my solution was to make dictionary based config to allow rabbitmq support for example.

2) I understand that you might not want to overwrite variables and we have solved that but might be very specific to us.

Thank you for your reply :+1:  will maintain another branch
